(function(){
  'use strict';
  const S=window.CapitalAIScoring,P=window.CapitalAIProviders,$=s=>document.querySelector(s);let assets=[],selected=null,tf='1d';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pill=(el,state,text)=>{el.textContent=text;el.className='pill '+(state==='PASS'?'ok':state==='WARN'?'warn':'bad')};
  function draw(rows){const canvas=$('#chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,series=S.normalizeSeries(rows).slice(-90);ctx.clearRect(0,0,w,h);ctx.fillStyle='#030711';ctx.fillRect(0,0,w,h);if(!series.length)return;const hasOhlc=series.every(x=>x.kind==='ohlcv'),hi=Math.max(...series.map(x=>hasOhlc?x.high:x.close)),lo=Math.min(...series.map(x=>hasOhlc?x.low:x.close)),pad=24,dx=(w-pad*2)/Math.max(1,series.length-1),y=v=>pad+(hi-v)/(hi-lo||1)*(h-pad*2);ctx.strokeStyle='#17233a';ctx.lineWidth=1;for(let g=0;g<5;g++){const yy=pad+g*(h-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(w-pad,yy);ctx.stroke()}if(!hasOhlc){ctx.strokeStyle='#f5b014';ctx.lineWidth=2;ctx.beginPath();series.forEach((b,i)=>{const x=pad+i*dx,yy=y(b.close);if(i===0)ctx.moveTo(x,yy);else ctx.lineTo(x,yy)});ctx.stroke();return}series.forEach((b,i)=>{const x=pad+i*dx,up=b.close>=b.open;ctx.strokeStyle=up?'#52df94':'#ff6b7a';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x,y(b.high));ctx.lineTo(x,y(b.low));ctx.stroke();const top=y(Math.max(b.open,b.close)),bottom=y(Math.min(b.open,b.close));ctx.fillRect(x-Math.max(1,dx*.23),top,Math.max(2,dx*.46),Math.max(1,bottom-top))})}
  function renderPatterns(patterns){$('#patterns').innerHTML=patterns.length?patterns.map(p=>`<div class="pattern"><b>${esc(p.name)}</b><span>${p.signal==='long'?'LONG':'SHORT'} · ${'🪐'.repeat(p.priority)}</span><small class="muted">${p.rangeLow.toFixed(2)}–${p.rangeHigh.toFixed(2)} · ${esc(p.indicators.join(', '))}</small></div>`).join(''):'<div class="muted">Keine bestätigte OHLCV-Pattern-Evidence verfügbar.</div>';const max=Math.max(0,...patterns.map(p=>p.priority));$('#patternPriority').textContent=max?'🪐'.repeat(max):'—'}
  function renderScore(score){$('#scoreValue').textContent=score.final_score??'—';$('#scoreMeta').textContent=`${score.integrity.modelId}@${score.integrity.modelVersion} · Coverage ${Math.round(score.integrity.coverage*100)}% · ${score.status}`;$('#factorGrid').innerHTML=Object.entries(score.values).map(([k,v])=>`<div class="factor"><small>${esc(k)}</small><b>${Number.isFinite(v)?Number(v).toFixed(1):'—'}</b></div>`).join('')}
  function updateQa(){const states=[$('#qaLogin'),$('#qaData'),$('#qaScore')].map(x=>x.classList.contains('ok'));document.documentElement.dataset.login=states[0]?'PASS':'FAIL';document.documentElement.dataset.data=states[1]?'PASS':'FAIL';document.documentElement.dataset.score=states[2]?'PASS':'FAIL';document.documentElement.dataset.quality=states.every(Boolean)?'PASS':'FAIL'}
  async function refresh(){if(!selected)return;$('#sourceLine').textContent='Daten werden geladen…';try{const dailyPromise=tf==='1d'?null:P.marketSeries(selected,'1d');const [chartSeries,dailySeries,sent]=await Promise.all([P.marketSeries(selected,tf),dailyPromise||P.marketSeries(selected,'1d'),P.sentiment()]);draw(chartSeries);renderPatterns(S.detectPatterns(chartSeries));const score=S.evaluate(selected.symbol,dailySeries,selected);renderScore(score);$('#sentiment').textContent=sent.points===null?'—':`${sent.points} · ${sent.label||''}`;const src=chartSeries[0]?.source||'Unknown';$('#sourceLine').textContent=`${src} · ${tf} · CoinPaprika Rank #${selected.rank} · ${chartSeries[0]?.kind==='point'?'Line (keine OHLC-Erfindung)':'echte OHLCV'}`;const dataOk=dailySeries.length>=20&&chartSeries.length>0;pill($('#qaData'),dataOk?'PASS':'FAIL',`Daten ${dataOk?'PASS':'FAIL'}`);pill($('#qaScore'),score.status==='READY'?'PASS':'FAIL',`Scoring ${score.status==='READY'?'PASS':'FAIL'}`);$('#modelAuthority').textContent=`Local Authority: ${score.integrity.modelId}@${score.integrity.modelVersion} · Finance-Provenance`updateQa()}catch(e){$('#sourceLine').textContent='Fehler: '+e.message;pill($('#qaData'),'FAIL','Daten FAIL');pill($('#qaScore'),'FAIL','Scoring FAIL');updateQa()}}
  async function boot(){try{const session=await P.session();pill($('#qaLogin'),session.configured&&session.authenticated?'PASS':'WARN',`Login ${session.authenticated?'PASS':'ANMELDUNG NÖTIG'}`);$('#authState').textContent=session.authenticated?`Angemeldet · ${session.user?.name||'Benutzer'}`:'Nicht angemeldet';$('#loginButton').style.display=session.authenticated?'none':'inline-block'}catch(e){pill($('#qaLogin'),'FAIL','Login FAIL');$('#authState').textContent='Auth nicht erreichbar'}try{assets=await P.universe();const select=$('#assetSelect');select.innerHTML=assets.map(a=>`<option value="${esc(a.symbol)}">${a.rank}. ${esc(a.name)} (${esc(a.symbol)})</option>`).join('');selected=assets.find(a=>a.symbol==='BTC')||assets[0];if(selected)select.value=selected.symbol;select.onchange=()=>{selected=assets.find(a=>a.symbol===select.value);refresh()};await refresh()}catch(e){pill($('#qaData'),'FAIL','Top-400 FAIL');$('#sourceLine').textContent='Universe Fehler: '+e.message;updateQa()}updateQa()}
  $('#loginButton').onclick=()=>P.login();$('#refreshButton').onclick=refresh;document.querySelectorAll('[data-tf]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tf]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tf=b.dataset.tf;refresh()});boot();
})();