(function(){
  'use strict';
  const S=window.CapitalAIScoring,P=window.CapitalAIProviders;
  const $=s=>document.querySelector(s);
  let assets=[],selected=null,tf='1d',lastBars=[];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pill=(el,state,text)=>{el.textContent=text;el.className='pill '+(state==='PASS'?'ok':state==='WARN'?'warn':'bad')};
  function draw(bars){const canvas=$('#chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#030711';ctx.fillRect(0,0,w,h);const rows=bars.slice(-70);if(!rows.length)return;const hi=Math.max(...rows.map(x=>x.high)),lo=Math.min(...rows.map(x=>x.low)),pad=24,dx=(w-pad*2)/rows.length,y=v=>pad+(hi-v)/(hi-lo||1)*(h-pad*2);ctx.strokeStyle='#17233a';ctx.lineWidth=1;for(let g=0;g<5;g++){const yy=pad+g*(h-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(w-pad,yy);ctx.stroke()}rows.forEach((b,i)=>{const x=pad+i*dx+dx/2,up=b.close>=b.open;ctx.strokeStyle=up?'#52df94':'#ff6b7a';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x,y(b.high));ctx.lineTo(x,y(b.low));ctx.stroke();const top=y(Math.max(b.open,b.close)),bottom=y(Math.min(b.open,b.close));ctx.fillRect(x-dx*.27,top,Math.max(1,dx*.54),Math.max(1,bottom-top))})}
  function renderPatterns(patterns){$('#patterns').innerHTML=patterns.length?patterns.map(p=>`<div class="pattern"><b>${esc(p.name)}</b><span>${p.signal==='long'?'LONG':'SHORT'} · ${'🪐'.repeat(p.priority)}</span><small class="muted">${p.rangeLow.toFixed(2)}–${p.rangeHigh.toFixed(2)} · ${esc(p.indicators.join(', '))}</small></div>`).join(''):'<div class="muted">Kein aktives Muster.</div>';const max=Math.max(0,...patterns.map(p=>p.priority));$('#patternPriority').textContent=max?'🪐'.repeat(max):'—'}
  function renderScore(score){$('#scoreValue').textContent=score.final_score??'—';$('#scoreMeta').textContent=`${score.integrity.modelId}@${score.integrity.modelVersion} · Coverage ${Math.round(score.integrity.coverage*100)}% · ${score.status}`;$('#factorGrid').innerHTML=Object.entries(score.values).map(([k,v])=>`<div class="factor"><small>${esc(k)}</small><b>${Number.isFinite(v)?Number(v).toFixed(1):'—'}</b></div>`).join('')}
  async function refresh(){if(!selected)return;$('#sourceLine').textContent='Daten werden geladen…';try{const [chartBars,dailyBars,sent]=await Promise.all([P.klines(selected.symbol,tf),tf==='1d'?P.klines(selected.symbol,'1d'):P.klines(selected.symbol,'1d'),P.sentiment()]);lastBars=chartBars;draw(chartBars);renderPatterns(S.detectPatterns(chartBars));const score=S.evaluate(selected.symbol,dailyBars,selected);renderScore(score);$('#sentiment').textContent=sent.points===null?'—':`${sent.points} · ${sent.label||''}`;$('#sourceLine').textContent=`Binance OHLCV · ${tf} · CoinPaprika Rank #${selected.rank}`;pill($('#qaData'),chartBars.length>=40?'PASS':'FAIL',`Daten ${chartBars.length>=40?'PASS':'FAIL'}`);pill($('#qaScore'),score.status==='READY'?'PASS':'FAIL',`Scoring ${score.status==='READY'?'PASS':'FAIL'}`);try{const remote=await P.remoteScore(selected.symbol,selected.name);const r=Number(remote.final_score);$('#remoteCompare').textContent=Number.isFinite(r)&&score.final_score!==null?`Server-Drift: ${(score.final_score-r).toFixed(2)} Punkte`:'Server-Vergleich verfügbar, aber ohne vergleichbaren Score.'}catch(e){$('#remoteCompare').textContent='Server-Vergleich nicht verfügbar: '+e.message}updateQa()}catch(e){$('#sourceLine').textContent='Fehler: '+e.message;pill($('#qaData'),'FAIL','Daten FAIL');pill($('#qaScore'),'FAIL','Scoring FAIL');updateQa()}}
  function updateQa(){const states=[$('#qaLogin'),$('#qaData'),$('#qaScore')].map(x=>x.classList.contains('ok'));document.documentElement.dataset.login=states[0]?'PASS':'FAIL';document.documentElement.dataset.data=states[1]?'PASS':'FAIL';document.documentElement.dataset.score=states[2]?'PASS':'FAIL';document.documentElement.dataset.quality=states.every(Boolean)?'PASS':'FAIL'}
  async function boot(){try{const session=await P.session();pill($('#qaLogin'),session.configured&&session.authenticated?'PASS':'WARN',`Login ${session.authenticated?'PASS':'ANMELDUNG NÖTIG'}`);$('#authState').textContent=session.authenticated?`Angemeldet · ${session.user?.name||'Benutzer'}`:'Nicht angemeldet';$('#loginButton').style.display=session.authenticated?'none':'inline-block'}catch(e){pill($('#qaLogin'),'FAIL','Login FAIL');$('#authState').textContent='Auth nicht erreichbar'}try{assets=await P.universe();const select=$('#assetSelect');select.innerHTML=assets.map(a=>`<option value="${esc(a.symbol)}">${a.rank}. ${esc(a.name)} (${esc(a.symbol)})</option>`).join('');selected=assets.find(a=>a.symbol==='BTC')||assets[0];if(selected)select.value=selected.symbol;select.onchange=()=>{selected=assets.find(a=>a.symbol===select.value);refresh()};await refresh()}catch(e){pill($('#qaData'),'FAIL','Top-400 FAIL');$('#sourceLine').textContent='Universe Fehler: '+e.message;updateQa()}updateQa()}
  $('#loginButton').onclick=()=>P.login();$('#refreshButton').onclick=refresh;document.querySelectorAll('[data-tf]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tf]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tf=b.dataset.tf;refresh()});boot();
})();