/* @license Proprietary CAPITAL-AI; scoring primitives derived from Finance Apache-2.0-marked sources. */
(function(root){
  'use strict';
  const MODEL_ID='crypto-technical-provenance',MODEL_VERSION='0.7.0',FEATURE_VERSION='crypto-technical-features/0.7.0',RESULT_VERSION='scoring-integrity/1.1.0';
  const WEIGHTS=Object.freeze({trend:.2222222222,momentum:.1777777778,volatility_quality:.1333333333,breakout_quality:.1111111111,relative_strength:.1333333333,avg_daily_volume:.0888888889,supply_dynamics:.0888888889,data_quality_risk:.0444444445});
  const INVERTED=new Set(['data_quality_risk']);
  const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,v));
  function finite(n){return Number.isFinite(Number(n))?Number(n):undefined}
  function computeReturnStats(closes){if(!Array.isArray(closes)||closes.length<3)return undefined;const rs=[];for(let i=1;i<closes.length;i++){if(closes[i-1]>0&&closes[i]>0)rs.push(Math.log(closes[i]/closes[i-1]));}if(rs.length<2)return undefined;const mean=rs.reduce((a,b)=>a+b,0)/rs.length;const variance=rs.reduce((a,b)=>a+(b-mean)**2,0)/rs.length;const first=closes[0],last=closes.at(-1);return{dailyStdevPct:Math.sqrt(variance)*100,rocPct:first>0?((last-first)/first)*100:0,sma:closes.reduce((a,b)=>a+b,0)/closes.length,last,high:Math.max(...closes),low:Math.min(...closes)}}
  function computeRsi(closes){if(!closes||closes.length<3)return undefined;let g=0,l=0;for(let i=1;i<closes.length;i++){const d=closes[i]-closes[i-1];if(d>=0)g+=d;else l-=d;}g/=closes.length-1;l/=closes.length-1;if(l===0)return 100;return clamp(100-100/(1+g/l))}
  const scoreTrend=(last,sma)=>sma>0?clamp(50+((last-sma)/sma)*100*2):50;
  const scoreMomentum=roc=>clamp(50+roc*1.5);
  const scoreVolatility=stdev=>clamp((stdev/15)*100);
  const scoreBreakout=(last,high,low)=>high>low?clamp(((last-low)/(high-low))*100):50;
  const scoreLiquidity=(volume,cap)=>Number.isFinite(volume)&&Number.isFinite(cap)&&cap>0?clamp(((volume/cap)/.30)*100):undefined;
  const scoreTokenomics=(circ,max)=>Number.isFinite(circ)&&Number.isFinite(max)&&max>0?clamp((circ/max)*100):undefined;
  function renormalize(values){let sum=0,weighted=0;const used=[],missing=[];for(const [k,w] of Object.entries(WEIGHTS)){const v=values[k];if(Number.isFinite(v)){sum+=w;used.push(k)}else missing.push(k)}if(sum<=0)return{score:0,used,missing};for(const k of used){const v=INVERTED.has(k)?100-values[k]:values[k];weighted+=v*(WEIGHTS[k]/sum)}return{score:clamp(weighted),used,missing}}
  const thresholds=[{low:90,label:'A_setup',name:'A-Setup'},{low:80,label:'tradeable_watch',name:'Tradeable Watch'},{low:70,label:'speculative_watch',name:'Speculative Watch'},{low:60,label:'observe',name:'Observe'},{low:0,label:'reject',name:'Reject'}];
  function normalizeBars(rows){return (rows||[]).map(x=>({time:Number(x.time),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),volume:Number(x.volume)})).filter(b=>[b.time,b.open,b.high,b.low,b.close,b.volume].every(Number.isFinite)&&b.high>=Math.max(b.open,b.close)&&b.low<=Math.min(b.open,b.close)).sort((a,b)=>a.time-b.time)}
  function snapshotFactors(snapshot){const q=snapshot?.quotes?.USD||{};return{avg_daily_volume:scoreLiquidity(finite(q.volume_24h),finite(q.market_cap)),supply_dynamics:scoreTokenomics(finite(snapshot?.circulating_supply),finite(snapshot?.max_supply))}}
  function evaluate(symbol,bars,snapshot){const s=String(symbol||'').trim().toUpperCase();const clean=normalizeBars(bars);const recent=clean.slice(-30);const closes=recent.map(b=>b.close);const stats=computeReturnStats(closes);const rsi=computeRsi(closes);const snap=snapshotFactors(snapshot);const values={trend:stats?scoreTrend(stats.last,stats.sma):undefined,momentum:stats?scoreMomentum(stats.rocPct):undefined,volatility_quality:stats?100-scoreVolatility(stats.dailyStdevPct):undefined,breakout_quality:stats?scoreBreakout(stats.last,stats.high,stats.low):undefined,relative_strength:rsi,avg_daily_volume:snap.avg_daily_volume,supply_dynamics:snap.supply_dynamics,data_quality_risk:clean.length>=20?5:undefined};const calc=renormalize(values);const coverage=calc.used.length/Object.keys(WEIGHTS).length;const last=clean.at(-1);const age=last?Date.now()-last.time*1000:Infinity;const status=clean.length<20?'INSUFFICIENT_HISTORY':coverage<.5?'DATA_UNAVAILABLE':age>4*86400000?'STALE_DATA':'READY';const decision=thresholds.find(t=>calc.score>=t.low)||thresholds.at(-1);const evidence=[];if(last)evidence.push({id:`binance-history:${s}:${last.time}`,source:'Binance',observedAt:new Date(last.time*1000).toISOString(),retrievedAt:new Date().toISOString(),kind:'market-history'});if(snapshot)evidence.push({id:`coinpaprika-snapshot:${s}:${snapshot.rank||'na'}`,source:'CoinPaprika',observedAt:new Date().toISOString(),retrievedAt:new Date().toISOString(),kind:'market-snapshot'});return{status,score:status==='READY'?Number((calc.score/10).toFixed(1)):null,final_score:status==='READY'?Number(calc.score.toFixed(2)):null,decision:status==='READY'?decision.label:'not_computable',decisionName:status==='READY'?decision.name:'Nicht berechenbar',weights:WEIGHTS,values,usedFactors:calc.used,missingFactors:calc.missing,integrity:{status,assetId:`crypto:${s}`,providers:[...new Set(evidence.map(e=>e.source))],retrievedAt:new Date().toISOString(),dataQuality:coverage>=.7?'high':coverage>=.5?'medium':'low',featureVersion:FEATURE_VERSION,scoringVersion:MODEL_ID+'/'+MODEL_VERSION,coverage:Number(coverage.toFixed(3)),evidence,missingFields:calc.missing,modelId:MODEL_ID,modelVersion:MODEL_VERSION,resultContractVersion:RESULT_VERSION,mobileProjection:'mobile-finance-kernel/1.0.0'}}}
  function ema(values,p){if(values.length<p)return NaN;const k=2/(p+1);let e=values.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<values.length;i++)e=values[i]*k+e*(1-k);return e}
  function detectPatterns(rows){const b=normalizeBars(rows);if(b.length<22)return[];const i=b.length-1,last=b[i],prev=b[i-1],closes=b.map(x=>x.close),volAvg=b.slice(-21,-1).reduce((a,x)=>a+x.volume,0)/20,priorHigh=Math.max(...b.slice(-21,-1).map(x=>x.high)),priorLow=Math.min(...b.slice(-21,-1).map(x=>x.low)),rsi=computeRsi(closes.slice(-15))||50,patterns=[];const add=(id,name,signal,priority,low,high,indicators)=>patterns.push({id,name,signal,priority,rangeLow:low,rangeHigh:high,indicators});if(last.close>priorHigh)add('breakout','20-Bar Breakout','long',last.volume>volAvg*1.5?5:4,priorHigh,last.close,['20-Bar High','Volume']);if(last.close<priorLow)add('breakdown','20-Bar Breakdown','short',last.volume>volAvg*1.5?5:4,last.close,priorLow,['20-Bar Low','Volume']);const bull=last.close>last.open&&prev.close<prev.open&&last.close>=prev.open&&last.open<=prev.close;const bear=last.close<last.open&&prev.close>prev.open&&last.close<=prev.open&&last.open>=prev.close;if(bull)add('engulf-bull','Bullish Engulfing','long',rsi<70?3:2,last.low,last.high,['Candles','RSI']);if(bear)add('engulf-bear','Bearish Engulfing','short',rsi>30?3:2,last.low,last.high,['Candles','RSI']);const e12=ema(closes,12),e26=ema(closes,26),e50=ema(closes,50);if(e12>e26&&e26>e50)add('ema-stack-bull','EMA 12/26/50 Stack','long',4,e50,e12,['EMA12','EMA26','EMA50']);if(e12<e26&&e26<e50)add('ema-stack-bear','EMA 12/26/50 Stack','short',4,e12,e50,['EMA12','EMA26','EMA50']);if(last.low<prev.low&&last.close>prev.low&&last.close>last.open)add('sweep-bull','Liquidity Sweep','long',3,last.low,prev.low,['Liquidity','Candle']);if(last.high>prev.high&&last.close<prev.high&&last.close<last.open)add('sweep-bear','Liquidity Sweep','short',3,prev.high,last.high,['Liquidity','Candle']);return patterns.sort((a,b)=>b.priority-a.priority)}
  const api={MODEL_ID,MODEL_VERSION,FEATURE_VERSION,RESULT_VERSION,WEIGHTS,computeReturnStats,computeRsi,evaluate,detectPatterns,renormalize};
  root.CapitalAIScoring=api;
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
